import {initializeApp} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import {getFirestore,collection,doc,getDoc,setDoc,addDoc,updateDoc,deleteDoc,onSnapshot,query,orderBy,limit,serverTimestamp} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";
import {firebaseConfig} from "./firebase-config.js";
const app=initializeApp(firebaseConfig),db=getFirestore(app),$=id=>document.getElementById(id),$$=s=>[...document.querySelectorAll(s)];
const roles={leader:"Líder",manager:"Gerente",member:"Membro"};let user=null,profile=null,unsubs=[],calendarDate=new Date(),selectedDateKey="";
const cache={users:[],members:[],missions:[],partnerships:[],notices:[],events:[],points:[],discipline:[],history:[],products:[],vault:[],goals:[]};
const cleanPassport=v=>String(v||"").trim().replace(/\D/g,"");const safe=(v="")=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const dateValue=v=>{if(!v)return null;if(v.toDate)return v.toDate();const d=new Date(v);return isNaN(d)?null:d};const fmt=v=>{const d=dateValue(v);return d?d.toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"}):"—"};
const money=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0});const canManage=()=>["leader","manager"].includes(profile?.role),isLeader=()=>profile?.role==="leader";
function toast(msg,bad=false){const e=$("toast");e.textContent=msg;e.className=`toast show${bad?" error":""}`;clearTimeout(window.__t);window.__t=setTimeout(()=>e.className="toast",3200)}
function bytesToBase64(bytes){return btoa(String.fromCharCode(...bytes))}function base64ToBytes(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function hashPassword(password,saltB64){const salt=saltB64?base64ToBytes(saltB64):crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:150000,hash:'SHA-256'},key,256);return{salt:bytesToBase64(salt),hash:bytesToBase64(new Uint8Array(bits))}}
async function verifyPassword(password,salt,hash){return(await hashPassword(password,salt)).hash===hash}
async function compressImage(file,max=1200,quality=.72){return new Promise((resolve,reject)=>{const img=new Image(),r=new FileReader();r.onload=()=>{img.onload=()=>{let w=img.width,h=img.height;if(w>max||h>max){const ratio=Math.min(max/w,max/h);w=Math.round(w*ratio);h=Math.round(h*ratio)}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);resolve(c.toDataURL('image/jpeg',quality))};img.onerror=reject;img.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
async function log(action,target="",details=""){if(!user||!profile)return;try{await addDoc(collection(db,"history"),{action,target,details,userId:user.uid,userName:profile.name,createdAt:serverTimestamp()})}catch(e){console.warn(e)}}
function showAuth(which='login'){['loginForm','firstAccessForm','setupForm'].forEach(id=>$(id).classList.toggle('hidden',id!==which+'Form'))}
$("showFirstAccess").onclick=()=>showAuth('firstAccess');$("backToLogin").onclick=()=>showAuth('login');$("backToLogin2").onclick=()=>showAuth('login');
async function boot(){const setup=await getDoc(doc(db,'system','setup'));if(!setup.exists()){showAuth('setup');return}const session=localStorage.getItem('hh_session');if(session){const snap=await getDoc(doc(db,'users',session));if(snap.exists()&&snap.data().active!==false&&!snap.data().mustSetPassword){profile={id:snap.id,...snap.data()};user={uid:snap.id};openApp();listen();return}}showAuth('login')}
$("setupForm").onsubmit=async e=>{e.preventDefault();const out=$("setupError"),name=$("setupName").value.trim(),passport=cleanPassport($("setupPassport").value),pw=$("setupPassword").value,cp=$("setupPasswordConfirm").value;out.textContent='';if(!name||!passport)return out.textContent='Preencha nome e passaporte.';if(pw!==cp)return out.textContent='As senhas não são iguais.';try{const setupRef=doc(db,'system','setup');if((await getDoc(setupRef)).exists())throw Error('Já existe um Líder configurado.');const cred=await hashPassword(pw);await setDoc(doc(db,'users',passport),{name,passport,role:'leader',active:true,mustSetPassword:false,passwordHash:cred.hash,passwordSalt:cred.salt,createdAt:serverTimestamp()});await setDoc(setupRef,{initialized:true,leaderPassport:passport,createdAt:serverTimestamp()});profile={id:passport,name,passport,role:'leader',active:true};user={uid:passport};localStorage.setItem('hh_session',passport);openApp();listen()}catch(err){out.textContent=err.message||'Não foi possível criar o Líder.'}}
$("loginForm").onsubmit=async e=>{e.preventDefault();const out=$("loginError"),p=cleanPassport($("loginPassport").value),pw=$("loginPassword").value;out.textContent='';try{const snap=await getDoc(doc(db,'users',p));if(!snap.exists())throw Error('invalid');const data=snap.data();if(data.active===false)throw Error('blocked');if(data.mustSetPassword||!data.passwordHash)throw Error('first');if(!(await verifyPassword(pw,data.passwordSalt,data.passwordHash)))throw Error('invalid');profile={id:p,...data};user={uid:p};localStorage.setItem('hh_session',p);openApp();listen()}catch(err){out.textContent=err.message==='blocked'?'Seu acesso está bloqueado.':err.message==='first'?'Use “Primeiro acesso” para criar sua senha.':'Passaporte ou senha incorretos.'}}
$("firstAccessForm").onsubmit=async e=>{e.preventDefault();const out=$("firstAccessError"),passport=cleanPassport($("firstPassport").value),pw=$("firstPassword").value,cp=$("firstPasswordConfirm").value;out.textContent='';if(pw!==cp)return out.textContent='As senhas não são iguais.';try{const ref=doc(db,'users',passport),snap=await getDoc(ref);if(!snap.exists())throw Error('not-authorized');const data=snap.data();if(data.active===false)throw Error('blocked');if(!data.mustSetPassword&&data.passwordHash)throw Error('already');const cred=await hashPassword(pw);await updateDoc(ref,{passwordHash:cred.hash,passwordSalt:cred.salt,mustSetPassword:false,updatedAt:serverTimestamp()});profile={id:passport,...data,...cred,mustSetPassword:false};user={uid:passport};localStorage.setItem('hh_session',passport);openApp();listen()}catch(err){out.textContent=err.message==='not-authorized'?'Esse passaporte ainda não foi autorizado.':err.message==='blocked'?'Seu acesso está bloqueado.':err.message==='already'?'Esse passaporte já possui senha.':'Não foi possível ativar o acesso.'}}
$("logoutBtn").onclick=()=>{localStorage.removeItem('hh_session');stop();user=profile=null;$("appView").classList.add('hidden');$("authView").classList.remove('hidden');showAuth('login')};
function updateAvatar(){const img=$("sidebarAvatar"),initial=$("userInitial");if(profile.avatarData){img.src=profile.avatarData;img.classList.remove('hidden');initial.classList.add('hidden')}else{img.classList.add('hidden');initial.classList.remove('hidden');initial.textContent=(profile.name||'H')[0].toUpperCase()}}
function openApp(){$("authView").classList.add("hidden");$("appView").classList.remove("hidden");const name=profile.name||profile.passport;$("sidebarUserName").textContent=name;$("sidebarUserRole").textContent=roles[profile.role];$("topUserBadge").textContent=roles[profile.role];$("welcomeName").textContent=name.split(" ")[0];updateAvatar();$$('.leader-only').forEach(x=>x.classList.toggle('hidden',!isLeader()));$$('.manager-only').forEach(x=>x.classList.toggle('hidden',!canManage()));switchPage("dashboard")}
function stop(){unsubs.forEach(f=>f());unsubs=[]}function sub(name,ordered=false){let q=collection(db,name);if(ordered)q=query(q,orderBy("createdAt","desc"));unsubs.push(onSnapshot(q,s=>{cache[name]=s.docs.map(d=>({id:d.id,...d.data()}));renderAll()},e=>console.warn(name,e)))}
function listen(){["members","missions","partnerships","notices","events","points","discipline","products","vault","goals"].forEach(n=>sub(n,["notices","points","discipline","vault","goals"].includes(n)));sub("users");if(isLeader())unsubs.push(onSnapshot(query(collection(db,"history"),orderBy("createdAt","desc"),limit(200)),s=>{cache.history=s.docs.map(d=>({id:d.id,...d.data()}));renderAll()}));ensureDefaultProduct()}
async function ensureDefaultProduct(){if(!canManage())return;const snap=await getDoc(doc(db,'products','metanfetamina'));if(!snap.exists())await setDoc(doc(db,'products','metanfetamina'),{name:'Metanfetamina',partnerPrice:200,regularPrice:250,createdAt:serverTimestamp()})}
const pages={dashboard:"Dashboard",members:"Membros",missions:"Missões",partnerships:"Parcerias",notices:"Avisos",calculator:"Calculadora",vault:"Controle do Baú",goals:"Metas",calendar:"Calendário",ranking:"Pontos e ranking",discipline:"Disciplina",access:"Acessos",history:"Histórico"};
function switchPage(page){if((page==='access'||page==='history')&&!isLeader())return;if(page==='discipline'&&!canManage())return;$$('.page').forEach(x=>x.classList.remove('active'));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$(page+'Page')?.classList.add('active');$("pageTitle").textContent=pages[page];$("sidebar").classList.remove("open");if(page==='calendar')renderCalendar();if(page==='calculator')renderCalculator()}
$("mainNav").onclick=e=>{const b=e.target.closest('[data-page]');if(b)switchPage(b.dataset.page)};$("menuBtn").onclick=()=>$("sidebar").classList.toggle("open");
const defs={
member:{title:"membro",collection:"members",fields:[['name','Nome','text'],['passport','Passaporte','text'],['rank','Cargo no RP','text'],['status','Status','select',['Ativo','Afastado','Inativo']]]},
mission:{title:"missão",collection:"missions",fields:[['title','Nome da missão','text'],['date','Data e hora','datetime-local'],['leader','Líder da missão','text'],['participants','Participantes','textarea'],['objective','Objetivo','textarea'],['status','Status','select',['Planejada','Em andamento','Finalizada','Cancelada']],['points','Pontos por participação','number']]},
partnership:{title:"parceria",collection:"partnerships",fields:[['organization','Organização','text'],['responsible','Responsável','text'],['contact','Discord / contato','text'],['status','Status','select',['Ativa','Pendente','Encerrada']],['notes','Observações','textarea']]},
notice:{title:"aviso",collection:"notices",fields:[['title','Título','text'],['message','Mensagem','textarea'],['priority','Prioridade','select',['Normal','Importante','Urgente']]]},
event:{title:"evento",collection:"events",fields:[['title','Nome do evento','text'],['date','Data e hora','datetime-local'],['type','Tipo','select',['Evento importante','Reunião','Treinamento','Missão']],['location','Local','text'],['notes','Descrição','textarea']]},
points:{title:"pontuação",collection:"points",fields:[['memberName','Nome do membro','text'],['memberPassport','Passaporte','text'],['amount','Quantidade de pontos','number'],['reason','Motivo','text']]},
discipline:{title:"registro disciplinar",collection:"discipline",fields:[['memberName','Nome','text'],['memberPassport','Passaporte','text'],['level','Tipo','select',['Aviso','Advertência','Suspensão']],['status','Status','select',['Ativo','Cumprido','Cancelado']],['reason','Motivo','textarea']]},
access:{title:"acesso",collection:"users",fields:[['name','Nome','text'],['passport','Passaporte / ID','text'],['role','Cargo no site','select',[['member','Membro'],['manager','Gerente'],['leader','Líder']]]]},
product:{title:"produto",collection:"products",fields:[['name','Nome do produto','text'],['partnerPrice','Preço com parceria','number'],['regularPrice','Preço sem parceria','number']]},
password:{title:"senha",fields:[['password','Nova senha','password'],['confirm','Confirmar senha','password']]},
profile:{title:"perfil",fields:[['avatar','Foto de perfil','file']]}
};
function fieldHtml(f,val=''){const [key,label,type,opts]=f;if(type==='select'){const options=opts.map(o=>Array.isArray(o)?`<option value="${o[0]}" ${String(val)===o[0]?'selected':''}>${o[1]}</option>`:`<option ${String(val)===o?'selected':''}>${o}</option>`).join('');return`<label>${label}<select id="f_${key}">${options}</select></label>`}if(type==='textarea')return`<label class="full">${label}<textarea id="f_${key}" required>${safe(val)}</textarea></label>`;if(type==='file')return`<label class="full">${label}<input id="f_${key}" type="file" accept="image/*"><small class="muted">A imagem será reduzida automaticamente.</small></label>`;return`<label>${label}<input id="f_${key}" type="${type}" value="${safe(val)}" required></label>`}
function openModal(type,id=""){const d=defs[type];if(!d)return;if(!canManage()&&!['password','profile'].includes(type))return;if(type==='access'&&!isLeader())return;$("crudType").value=type;$("crudId").value=id;const item=id?cache[d.collection]?.find(x=>x.id===id):null;$("crudTitle").textContent=type==='profile'?'Minha foto de perfil':`${id?'Editar':'Novo'} ${d.title}`;$("crudFields").innerHTML=d.fields.map(f=>fieldHtml(f,item?.[f[0]]??'')).join('');$("crudModal").showModal()}
document.body.onclick=e=>{const n=e.target.closest('[data-new]');if(n)openModal(n.dataset.new);const ed=e.target.closest('[data-edit]');if(ed)openModal(ed.dataset.type,ed.dataset.edit);const del=e.target.closest('[data-delete]');if(del)removeRecord(del.dataset.type,del.dataset.delete);const tog=e.target.closest('[data-toggle-user]');if(tog)toggleUser(tog.dataset.toggleUser);const photo=e.target.closest('[data-photo]');if(photo){$("imageModalImg").src=photo.dataset.photo;$("imageModal").showModal()}};
$("closeModal").onclick=$("cancelModal").onclick=()=>$("crudModal").close();$("closeImageModal").onclick=()=>$("imageModal").close();
$("crudForm").onsubmit=async e=>{e.preventDefault();const type=$("crudType").value,d=defs[type],id=$("crudId").value,data={};for(const f of d.fields){const el=$("f_"+f[0]);if(f[2]!=='file')data[f[0]]=el.value.trim()}try{if(type==='profile'){const file=$("f_avatar").files[0];if(!file)throw Error('Escolha uma foto.');const avatarData=await compressImage(file,600,.78);await updateDoc(doc(db,'users',profile.passport),{avatarData,updatedAt:serverTimestamp()});profile.avatarData=avatarData;updateAvatar();$("crudModal").close();return toast('Foto de perfil atualizada.')}if(type==='password'){if(data.password!==data.confirm)throw Error('Senhas diferentes');if(data.password.length<6)throw Error('Senha curta');const cred=await hashPassword(data.password);await updateDoc(doc(db,'users',profile.passport),{passwordHash:cred.hash,passwordSalt:cred.salt,updatedAt:serverTimestamp()});$("crudModal").close();return toast('Senha alterada.')}if(type==='access'){const passport=cleanPassport(data.passport);if(!passport)throw Error('Passaporte inválido');const accessRef=doc(db,'users',passport),existing=await getDoc(accessRef);if(existing.exists()){await setDoc(accessRef,{name:data.name,passport,role:data.role,active:true,updatedAt:serverTimestamp(),updatedBy:user.uid},{merge:true})}else{await setDoc(accessRef,{name:data.name,passport,role:data.role,active:true,mustSetPassword:true,createdAt:serverTimestamp(),createdBy:user.uid})}await log(existing.exists()?'Acesso atualizado':'Passaporte autorizado',passport,roles[data.role])}else{data.updatedAt=serverTimestamp();if(type==='points'||type==='mission')data.points=data.points?Number(data.points):0;if(type==='points')data.amount=Number(data.amount);if(type==='product'){data.partnerPrice=Number(data.partnerPrice);data.regularPrice=Number(data.regularPrice)}if(id){await updateDoc(doc(db,d.collection,id),data);await log(`${cap(d.title)} atualizado`,data.title||data.name||data.memberName||id)}else{data.createdAt=serverTimestamp();data.authorName=profile.name;data.authorId=user.uid;await addDoc(collection(db,d.collection),data);await log(`${cap(d.title)} criado`,data.title||data.name||data.memberName||'registro')}}$("crudModal").close();toast('Registro salvo.')}catch(err){console.error(err);toast(err.message||'Não foi possível salvar.',true)}};
const cap=s=>s.charAt(0).toUpperCase()+s.slice(1);async function removeRecord(type,id){if(!canManage())return;if(!confirm('Excluir este registro?'))return;try{await deleteDoc(doc(db,defs[type].collection,id));await log(`${cap(defs[type].title)} excluído`,id);toast('Registro excluído.')}catch(e){toast('Não foi possível excluir.',true)}}
async function toggleUser(id){if(!isLeader()||id===user.uid)return;const u=cache.users.find(x=>x.id===id);await updateDoc(doc(db,'users',id),{active:u.active===false,updatedAt:serverTimestamp()});await log(u.active===false?'Acesso ativado':'Acesso bloqueado',u.passport)}
function edit(type,id){return canManage()?`<div class="actions"><button class="icon-btn" data-type="${type}" data-edit="${id}">Editar</button><button class="icon-btn danger" data-type="${type}" data-delete="${id}">Excluir</button></div>`:'—'}
function table(headers,rows){return rows.length?`<table class="data-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table>`:'<div class="empty">Nenhum registro encontrado.</div>'}
function renderAll(){renderDashboard();renderMembers();renderMissions();renderPartnerships();renderNotices();renderCalculator();renderVault();renderGoals();renderCalendar();renderRanking();renderDiscipline();renderAccess();renderHistory()}
function renderDashboard(){const activeMembers=cache.members.filter(x=>x.status==='Ativo').length,partners=cache.partnerships.filter(x=>x.status==='Ativa').length,missions=cache.missions.filter(x=>['Planejada','Em andamento'].includes(x.status)).length;const stats=[['Membros',activeMembers,'ativos'],['Missões',missions,'abertas'],['Parcerias',partners,'ativas'],['Avisos',cache.notices.length,'publicados'],['Baú',cache.vault.length,'movimentações'],['Metas',cache.goals.length,'publicadas'],['Eventos',cache.events.length,'agendados']];$("statsGrid").innerHTML=stats.map(s=>`<article class="stat-card"><span>${s[0]}</span><strong>${s[1]}</strong><small>${s[2]}</small></article>`).join('');$("recentMissions").innerHTML=cache.missions.filter(x=>x.status==='Planejada').slice(0,4).map(x=>`<div class="list-item"><div><strong>${safe(x.title)}</strong><p>${safe(x.leader||'Sem líder')} · ${safe(x.status)}</p></div><small>${fmt(x.date)}</small></div>`).join('')||'<div class="empty">Nenhuma missão planejada.</div>';$("recentNotices").innerHTML=cache.notices.slice(0,4).map(x=>`<div class="list-item"><div><strong>${safe(x.title)}</strong><p>${safe(x.message).slice(0,100)}</p></div><small>${fmt(x.createdAt)}</small></div>`).join('')||'<div class="empty">Nenhum aviso.</div>'}
function renderMembers(){const term=($("memberSearch")?.value||'').toLowerCase(),r=cache.members.filter(x=>`${x.name} ${x.passport} ${x.rank}`.toLowerCase().includes(term));$("membersTable").innerHTML=table(['Nome','Passaporte','Cargo','Status','Ações'],r.map(x=>`<tr><td>${safe(x.name)}</td><td>${safe(x.passport)}</td><td>${safe(x.rank)}</td><td><span class="status">${safe(x.status)}</span></td><td>${edit('member',x.id)}</td></tr>`))}$("memberSearch").oninput=renderMembers;
function renderMissions(){$("missionsTable").innerHTML=table(['Missão','Data','Líder','Status','Pontos','Ações'],cache.missions.map(x=>`<tr><td>${safe(x.title)}</td><td>${fmt(x.date)}</td><td>${safe(x.leader)}</td><td><span class="status">${safe(x.status)}</span></td><td>${safe(x.points||0)}</td><td>${edit('mission',x.id)}</td></tr>`))}
function renderPartnerships(){$("partnershipsTable").innerHTML=table(['Organização','Responsável','Contato','Status','Ações'],cache.partnerships.map(x=>`<tr><td>${safe(x.organization)}</td><td>${safe(x.responsible)}</td><td>${safe(x.contact||'—')}</td><td><span class="status">${safe(x.status)}</span></td><td>${edit('partnership',x.id)}</td></tr>`))}
function card(x,type,title,body,meta){return`<article class="content-card"><span class="eyebrow">${safe(meta||'REGISTRO')}</span><h4>${safe(title)}</h4><p>${safe(body)}</p><footer><span>${safe(x.authorName||'Hellhounds')}</span><span>${fmt(x.createdAt)}</span></footer>${canManage()?edit(type,x.id):''}</article>`}function renderNotices(){$("noticesList").innerHTML=cache.notices.map(x=>card(x,'notice',x.title,x.message,x.priority)).join('')||'<div class="empty">Nenhum aviso publicado.</div>'}
function renderCalculator(){const sel=$("calcProduct");if(!sel)return;const current=sel.value;sel.innerHTML=cache.products.map(x=>`<option value="${x.id}">${safe(x.name)}</option>`).join('')||'<option value="">Nenhum produto cadastrado</option>';if(cache.products.some(x=>x.id===current))sel.value=current;updateCalc();if($("productsTable"))$("productsTable").innerHTML=table(['Produto','Com parceria','Sem parceria','Ações'],cache.products.map(x=>`<tr><td>${safe(x.name)}</td><td>${money(x.partnerPrice)}</td><td>${money(x.regularPrice)}</td><td>${edit('product',x.id)}</td></tr>`))}
function updateCalc(){const p=cache.products.find(x=>x.id===$("calcProduct")?.value),qty=Number($("calcQuantity")?.value||0),partner=document.querySelector('input[name="partner"]:checked')?.value==='yes',unit=p?Number(partner?p.partnerPrice:p.regularPrice):0;$("unitPrice").textContent=money(unit);$("totalPrice").textContent=money(unit*qty)}
$("calcProduct").onchange=updateCalc;$("calcQuantity").oninput=updateCalc;$$('input[name="partner"]').forEach(x=>x.onchange=updateCalc);
async function setProofImage(file,previewId,zoneId){if(!file||!file.type?.startsWith('image/'))return toast('Use uma imagem PNG ou JPG.',true);try{const data=await compressImage(file,900,.7),preview=$(previewId),zone=$(zoneId);preview.innerHTML=`<div class="preview-wrap"><img src="${data}" alt="Prévia do comprovante"><button type="button" class="remove-proof" aria-label="Remover imagem">×</button></div>`;preview.dataset.image=data;preview.classList.remove('hidden');zone.classList.add('has-image')}catch(e){console.error(e);toast('Não foi possível carregar essa imagem.',true)}}
function setupPasteZone(inputId,zoneId,previewId){const input=$(inputId),zone=$(zoneId),preview=$(previewId);if(!input||!zone||!preview)return;zone.onclick=()=>input.click();zone.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();input.click()}};input.onchange=()=>setProofImage(input.files[0],previewId,zoneId);['dragenter','dragover'].forEach(type=>zone.addEventListener(type,e=>{e.preventDefault();zone.classList.add('dragging')}));['dragleave','drop'].forEach(type=>zone.addEventListener(type,e=>{e.preventDefault();zone.classList.remove('dragging')}));zone.addEventListener('drop',e=>setProofImage(e.dataTransfer?.files?.[0],previewId,zoneId));zone.addEventListener('paste',e=>{const file=[...(e.clipboardData?.items||[])].find(i=>i.type.startsWith('image/'))?.getAsFile();if(file){e.preventDefault();setProofImage(file,previewId,zoneId)}else toast('Nenhuma imagem encontrada na área de transferência.',true)});preview.onclick=e=>{if(!e.target.closest('.remove-proof'))return;preview.innerHTML='';preview.dataset.image='';preview.classList.add('hidden');zone.classList.remove('has-image');input.value=''}}
setupPasteZone('vaultImage','vaultDropZone','vaultPreview');
$("vaultForm").onsubmit=async e=>{e.preventDefault();const type=document.querySelector('input[name="vaultType"]:checked').value,items=$("vaultItems").value.trim(),imageData=$("vaultPreview").dataset.image;if(!items||!imageData)return toast('Preencha o item e envie o print.',true);try{await addDoc(collection(db,'vault'),{type,items,imageData,userName:profile.name,userPassport:profile.passport,userId:user.uid,createdAt:serverTimestamp()});await log(type==='deposit'?'Depósito no baú':'Retirada do baú',items);e.target.reset();$("vaultPreview").innerHTML='';$("vaultPreview").dataset.image='';$("vaultPreview").classList.add('hidden');$("vaultDropZone").classList.remove('has-image');toast('Movimentação registrada.')}catch(err){toast('Não foi possível salvar o print.',true)}};
$("vaultFilter").onchange=renderVault;function renderVault(){const filter=$("vaultFilter")?.value||'all',rows=cache.vault.filter(x=>filter==='all'||x.type===filter);$("vaultHistory").innerHTML=rows.map(x=>`<article class="vault-entry"><div class="vault-entry-head"><div><span class="vault-type ${x.type}">${x.type==='deposit'?'DEPÓSITO':'RETIRADA'}</span><h4>${safe(x.userName)}</h4></div><small>${fmt(x.createdAt)}</small></div><p><strong>${x.type==='deposit'?'Colocou':'Retirou'}:</strong> ${safe(x.items)}</p><button class="proof-btn" data-photo="${x.imageData}"><img src="${x.imageData}" alt="Print do baú"><span>Ver comprovante</span></button></article>`).join('')||'<div class="empty">Nenhuma movimentação registrada.</div>'}
function weekStart(v=new Date()){const d=new Date(v);d.setHours(0,0,0,0);const day=d.getDay();d.setDate(d.getDate()-(day===0?6:day-1));return d}
function sameWeek(v){const d=dateValue(v);if(!d)return false;const start=weekStart(),end=new Date(start);end.setDate(end.getDate()+7);return d>=start&&d<end}
async function notifyGoalDiscord(payload){const r=await fetch('/api/discord-meta',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok){const e=await r.json().catch(()=>({}));throw Error(e.error||'Falha ao enviar ao Discord')}}
setupPasteZone('goalImage','goalDropZone','goalPreview');
$("goalForm").onsubmit=async e=>{e.preventDefault();const bags=Number($("goalBags").value||0),description=$("goalDescription").value.trim(),imageData=$("goalPreview").dataset.image;if(!bags||!description||!imageData)return toast('Preencha os dados e envie a foto.',true);const now=new Date();if([0,6].includes(now.getDay()))return toast('A meta semanal é contabilizada de segunda a sexta.',true);try{const ref=await addDoc(collection(db,'goals'),{bags,weightKg:bags*100,description,imageData,userName:profile.name,userPassport:profile.passport,userId:user.uid,createdAt:serverTimestamp()});try{await notifyGoalDiscord({id:ref.id,bags,weightKg:bags*100,description,imageData,userName:profile.name,userPassport:profile.passport,submittedAt:now.toISOString()})}catch(err){console.warn(err);toast('Meta salva no site, mas o Discord não respondeu.',true)}await log('Meta concluída',`${bags} mochila(s)`,description);e.target.reset();$("goalBags").value='2';$("goalPreview").innerHTML='';$("goalPreview").dataset.image='';$("goalPreview").classList.add('hidden');$("goalDropZone").classList.remove('has-image');toast('Meta publicada com sucesso.')}catch(err){console.error(err);toast('Não foi possível publicar a meta.',true)}};
$("goalFilter").onchange=renderGoals;
function renderGoals(){if(!$("goalHistory"))return;const filter=$("goalFilter")?.value||'mine',weekly=cache.goals.filter(sameWeek),mine=weekly.filter(x=>x.userPassport===profile.passport),mineBags=mine.reduce((a,x)=>a+Number(x.bags||0),0),remaining=Math.max(0,10-mineBags),rows=(filter==='all'?weekly:mine);$("goalSummary").innerHTML=`<div class="goal-progress"><div><span>Seu progresso semanal</span><strong>${mineBags}/10 mochilas</strong><small>${mineBags*100} kg entregues · ${remaining?remaining+' restantes':'Meta concluída'}</small></div><div class="progress-track"><i style="width:${Math.min(100,mineBags*10)}%"></i></div></div>`;$("goalHistory").innerHTML=rows.map(x=>`<article class="vault-entry"><div class="vault-entry-head"><div><span class="vault-type deposit">META CONCLUÍDA</span><h4>${safe(x.userName)}</h4></div><small>${fmt(x.createdAt)}</small></div><p><strong>${safe(x.bags)} mochila(s)</strong> · ${safe(x.weightKg||Number(x.bags||0)*100)} kg</p><p>${safe(x.description)}</p><p class="muted">Passaporte: ${safe(x.userPassport)}</p><button class="proof-btn" data-photo="${x.imageData}"><img src="${x.imageData}" alt="Comprovante da meta"><span>Ver comprovante</span></button></article>`).join('')||'<div class="empty">Nenhuma meta publicada nesta semana.</div>'}
function dateKey(v){const d=dateValue(v);if(!d)return'';return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function renderCalendar(){if(!$("calendarGrid"))return;const y=calendarDate.getFullYear(),m=calendarDate.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),today=dateKey(new Date());$("calendarMonth").textContent=calendarDate.toLocaleDateString('pt-BR',{month:'long',year:'numeric'});let html='';for(let i=0;i<first.getDay();i++)html+='<button class="calendar-day blank" disabled></button>';for(let day=1;day<=last.getDate();day++){const key=`${y}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`,events=cache.events.filter(x=>dateKey(x.date)===key);html+=`<button class="calendar-day ${key===today?'today':''} ${key===selectedDateKey?'selected':''}" data-date="${key}"><span>${day}</span>${events.length?`<div class="event-dots">${events.slice(0,4).map(x=>`<i title="${safe(x.title)}"></i>`).join('')}</div>`:''}</button>`}$("calendarGrid").innerHTML=html;renderSelectedDay()}
$("calendarGrid").onclick=e=>{const b=e.target.closest('[data-date]');if(!b)return;selectedDateKey=b.dataset.date;renderCalendar()};$("prevMonth").onclick=()=>{calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()-1,1);selectedDateKey='';renderCalendar()};$("nextMonth").onclick=()=>{calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()+1,1);selectedDateKey='';renderCalendar()};
function renderSelectedDay(){const box=$("selectedDayEvents");if(!selectedDateKey){box.innerHTML='<div class="info-box">Clique em uma data para ver os eventos.</div>';return}const events=cache.events.filter(x=>dateKey(x.date)===selectedDateKey);box.innerHTML=`<h3>Eventos de ${new Date(selectedDateKey+'T12:00').toLocaleDateString('pt-BR')}</h3>`+(events.map(x=>`<div class="event-card"><div><span class="eyebrow">${safe(x.type)}</span><h4>${safe(x.title)}</h4><p>${safe(x.location||'Local não definido')} · ${safe(x.notes||'')}</p><small>${fmt(x.date)}</small></div>${canManage()?edit('event',x.id):''}</div>`).join('')||'<div class="empty">Nenhum evento nesta data.</div>')}
function renderRanking(){const sums={};cache.points.forEach(x=>{const k=x.memberPassport||x.memberName;if(!sums[k])sums[k]={passport:x.memberPassport,name:x.memberName,total:0};sums[k].total+=Number(x.amount)||0});const rows=Object.values(sums).sort((a,b)=>b.total-a.total);$("rankingTable").innerHTML=table(['Posição','Nome','Passaporte','Pontos'],rows.map((x,i)=>`<tr><td><strong>#${i+1}</strong></td><td>${safe(x.name)}</td><td>${safe(x.passport)}</td><td><strong>${x.total}</strong></td></tr>`))}
function renderDiscipline(){$("disciplineTable").innerHTML=table(['Membro','Passaporte','Registro','Status','Data','Ações'],cache.discipline.map(x=>`<tr><td>${safe(x.memberName)}</td><td>${safe(x.memberPassport)}</td><td>${safe(x.level)}</td><td><span class="status">${safe(x.status)}</span></td><td>${fmt(x.createdAt)}</td><td>${edit('discipline',x.id)}</td></tr>`))}
function renderAccess(){if(!isLeader())return;$("accessTable").innerHTML=table(['Nome','Passaporte','Cargo','Situação','Ação'],cache.users.map(x=>`<tr><td>${safe(x.name)}</td><td>${safe(x.passport)}</td><td>${safe(roles[x.role])}</td><td><span class="status">${x.active===false?'Bloqueado':x.mustSetPassword?'Aguardando primeiro acesso':'Ativo'}</span></td><td>${x.passport===profile.passport?'Conta atual':`<button class="icon-btn" data-toggle-user="${x.id}">${x.active===false?'Ativar':'Bloquear'}</button>`}</td></tr>`))}
function renderHistory(){if(!isLeader())return;$("historyList").innerHTML=cache.history.map(x=>`<div class="list-item"><div><strong>${safe(x.action)}</strong><p>${safe(x.userName)} · ${safe(x.target)} ${x.details?'· '+safe(x.details):''}</p></div><small>${fmt(x.createdAt)}</small></div>`).join('')||'<div class="empty">Nenhuma alteração registrada.</div>'}
boot().catch(e=>{console.error(e);toast('Erro ao iniciar o sistema.',true)});
